run:
  timeout: 10m
  go: "1.21.3"

linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - promlinter
    - protogetter
    - reassign
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - usetesting
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - whitespace
    - zerologlint
    - wastedassign
    # complexity: need to refactor
    # - wsl
    # - musttag
    # - perfsprint
    # - nestif
    # - mnd
    # - lll
    # - ireturn
    # - intrange
    # - godox
    # - gochecknoglobals
    # - funlen
    # - forcetypeassert
    # - fatcontext
    # - err113
    # - maintidx
    # - depguard
    # - cyclop
    # - copyloopvar
    # - revive
    # - predeclared
    # - gocognit
    # - errcheck
    # - gocyclo
    # - dupl
    # - wrapcheck
    # - tagliatelle
    # - tagalign
    # - inamedparam
    # - nonamedreturns
    # - recvcheck
    # - interfacebloat
    # - iface

issues:
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - usestdlibvars
        - testifylint
        - paralleltest

linters-settings:
  nlreturn:
    block-size: 5
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default  # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/Edge-Center)
  varnamelen:
    min-name-length: 1


