run:
  timeout: 10m
  go: "1.21.3"

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  enable-all: true
  disable:
    # deprecated
    - deadcode
    - maligned
    - varcheck
    - nosnakecase
    - interfacer
    - ifshort
    - structcheck
    - golint
    - scopelint
    - exhaustivestruct
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    # skip: dubious benefit
    - gochecknoglobals # Checks that no global variables exist.
    - exhaustruct      # Checks if all structure fields are initialized.
    - lll              # Reports long lines.
    - godox            # Tool for detection of FIXME, TODO and other comment keywords
    - wsl              # Whitespace Linter - Forces you to use empty lines!
    - tagliatelle      # Checks the struct tags.
    - nonamedreturns   # Reports all named returns.
    - wrapcheck        # Checks that errors returned from external packages are wrapped.
    - ireturn          # Accept Interfaces, Return Concrete Types.
    - tagalign         # Checks that struct tags are well aligned
    - depguard         # Checks if package imports are in a list of acceptable packages
    - musttag          # Enforce field tags in (un)marshaled structs.
    # complexity
    - cyclop           # Checks function and package cyclomatic complexity.
    # tests
    - testpackage      # Makes you use a separate _test package.
    - paralleltest     # Detects missing usage of t.Parallel() method in your Go test.

linters-settings:
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default  # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/Edge-Center)
  varnamelen:
    min-name-length: 1
