run:
  timeout: 60m
  go: "1.19"

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - asciicheck
    - errcheck
    - goimports
    - govet
    - ineffassign
    - nakedret
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - vet
    - vetshadow
