name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3

      - name: Linters
        run: make lint

      - name: Generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic

      - name: Check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./coverage.yml
          profile: cover.out
          threshold-file: 50
          threshold-package: 60
          threshold-total: 70
